version: "3"
services:
  test:
    image: wander_suite/db:test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=NotAValidDB
      - POSTGRES_USER=NotAValidUser
      - POSTGRES_PASSWORD=NotAValidPassword
    ports:
      - "5432:5432"
    container_name: wander-db-test
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/