name: Deploy Database

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

jobs:
  call-db-workflow:
    uses: wander-suite/wander-devops/.github/workflows/db-workflow.yml@main
